language: scala

script: sbt ++$TRAVIS_SCALA_VERSION scripted

after_script:
  - if [[ $TRAVIS_TEST_RESULT == 0 && 
          "$TRAVIS_REPO_SLUG" == "scoverage/sbt-scoverage" &&
          "$TRAVIS_BRANCH" == "master" ]]; then sbt "^publish"; fi

scala:
  - "2.10.6"

sudo: false
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache
