language: scala

script: sbt ^^$TRAVIS_SBT_VERSION scripted

matrix:
  include:
    - env: TRAVIS_SBT_VERSION="0.13.18"
    - env: TRAVIS_SBT_VERSION="1.3.0"

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_script:
  - sudo chmod +x /usr/local/bin/sbt
